blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

blogs/urls.py
"""define url patterns for blogs"""

from django.urls import path
from . import views

app_name = 'blogs'
urlpatterns = [
    # home page
    path('', views.index, name='index'),
    # page for adding new posts
    path('new_post/', views.new_post, name='new_post'),
    # page for editing existing posts
    path('edit_post/<int:post_id>', views.edit_post, name='edit_post'),
]

users/urls.py
"""defines URL patterns for users"""

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # include default auth urls
    path('', include('django.contrib.auth.urls')),
    # registration page
    path('register/', views.register, name='register'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class BlogPost(models.Model):
    title = models.CharField(max_length = 50)
    text = models.CharField(max_length = 200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms

from .models import BlogPost

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

blogs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import BlogPost
from .forms import BlogPostForm

def check_user_match(blog, request):
    if blog.owner != request.user:
        raise Http404

# Create your views here.
def index(request):
    """home page for blog"""
    blog_posts = BlogPost.objects.order_by('date_added')
    context = {'blog_posts': blog_posts}
    return render(request, 'blogs/index.html', context)

@login_required
def new_post(request):
    """add a new post"""
    if request.method != 'POST':
        # no data submitted ; create a blank form
        form = BlogPostForm
    else:
        # POST data submitted; process the data
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            return redirect('blogs:index')

    # display blank or invalid form
    context = {'form': form}
    return render(request, 'blogs/new_post.html', context)

@login_required
def edit_post(request, post_id):
    """edit existing post"""
    post = BlogPost.objects.get(id=post_id)

    check_user_match(post, request)

    if request.method != 'POST':
        # no data submitted ; pre-fill form with existing post
        form = BlogPostForm(instance=post)
    else:
        # POST data submitted; process the data
        form = BlogPostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:index')

    # display post with existing data or submit post to edit
    context = {'post': post, 'form': form}
    return render(request, 'blogs/edit_post.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):
    """register a new user"""
    if request.method != 'POST':
        # display a blank registration form
        form = UserCreationForm()
    else:
        # process completed form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # log the user in and then redirect to home page
            login(request, new_user)
            return redirect('blogs:index')
    
    # diaplay a blank or invalid form
    context = {'form': form}
    return render(request, 'registration/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0 shrink-to-fit=no">
    <title>Blog</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a href="{% url 'blogs:index' %}" class="navbar-brand">Blog</a> 

        <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">Hello, {{ user.username }}.</span>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'users:logout' %}" class="nav-link">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'users:register' %}" class="nav-link">Register</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'users:login' %}" class="nav-link">Log in</a>
                    </li>

                {% endif %}
            </ul>

        </div>
    
    
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
    
</body>
</html>

{% comment %} <p>
    <a href="{% url 'blogs:index' %}">Blog</a>
    {% if user.is_authenticated %}
        Hello, {{ user.username }}
        <a href="{% url 'users:logout' %}">Log out</a>
    {% else %}
        <a href="{% url 'users:register' %}">Register</a>
        <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
</p>

{% block content %}{% endblock content %} {% endcomment %}

blogs/templates/blogs/edit_post.html
{% extends 'blogs/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <h3>Edit Post</h3>
{% endblock page_header %}

{% block content %}

<form action="{% url 'blogs:edit_post' post.id %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Edit post</button>
    {% endbuttons %}
</form>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">Write a blog.</h1>

        <p class="lead">Write a blog and see what others are thinking as well</p>

        <a href="{% url 'users:register' %}" class="btn btn-lg btn-primary" role="button">Register &raquo;</a>

    </div>
{% endblock page_header %}

{% block content %}

<a href="{% url 'blogs:new_post' %}">Add a new post</a>

    {% for blog_post in blog_posts %}
        <div class="card mb-3">
            <h4 class="card-header">
            {{ blog_post.date_added|date:'M d, Y H:i' }}
            <small><a href="{% url 'blogs:edit_post' blog_post.id %}">Edit Post</a></small>
            </h4>
            <div class="card-body">
                {{ blog_post.text|linebreaks }}
            </div>
        </div>
        </li>
    {% empty %}
        <p>No blogposts added yet</p>
    {% endfor %}

{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends 'blogs/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <h3>Add a new post</h3>
{% endblock page_header %}

{% block content %}

<form action="{% url 'blogs:new_post' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Add post</button>
    {% endbuttons %}

</form>

{% endblock content %}